// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Connects;

#nullable disable

namespace app.Migrations.AppDbContextMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230427045838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app.Models.Group", b =>
                {
                    b.Property<int>("gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gid"));

                    b.Property<string>("decription")
                        .HasColumnType("ntext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("gid");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("app.Models.Location", b =>
                {
                    b.Property<int>("lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lid"));

                    b.Property<string>("author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("content")
                        .HasColumnType("ntext");

                    b.Property<float>("latitude")
                        .HasColumnType("real");

                    b.Property<float>("longtitude")
                        .HasColumnType("real");

                    b.Property<string>("pathimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("postdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("lid");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("app.Models.News", b =>
                {
                    b.Property<int>("nid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nid"));

                    b.Property<string>("author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("content")
                        .HasColumnType("ntext");

                    b.Property<string>("pathimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("postdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("nid");

                    b.ToTable("News");
                });

            modelBuilder.Entity("app.Models.ProgramInfo", b =>
                {
                    b.Property<int>("pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pid"));

                    b.Property<string>("content")
                        .HasColumnType("ntext");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("g_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("held_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("l_id")
                        .HasColumnType("int");

                    b.Property<string>("md5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pathimage_list")
                        .HasColumnType("ntext");

                    b.Property<int>("type_inoff")
                        .HasColumnType("int");

                    b.Property<int>("type_program")
                        .HasColumnType("int");

                    b.Property<int>("u_id")
                        .HasColumnType("int");

                    b.HasKey("pid");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("app.Models.Support", b =>
                {
                    b.Property<int>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sid"));

                    b.Property<string>("content")
                        .HasColumnType("ntext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("sid");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("app.Models.Ticket", b =>
                {
                    b.Property<int>("tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tid"));

                    b.Property<int>("inventory")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("Money");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("tid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("app.Models.Union", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uid"));

                    b.Property<string>("decription")
                        .HasColumnType("ntext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("uid");

                    b.ToTable("Unions");
                });
#pragma warning restore 612, 618
        }
    }
}
